#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAndSignup
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBH")]
	public partial class QLBHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public QLBHDataContext() : 
				base(global::LoginAndSignup.Properties.Settings.Default.QLBHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLBHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _f_ID;
		
		private string _f_Username;
		
		private string _f_Password;
		
		private string _f_Name;
		
		private string _f_Email;
		
		private System.DateTime _f_DOB;
		
		private int _f_Permission;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onf_IDChanging(int value);
    partial void Onf_IDChanged();
    partial void Onf_UsernameChanging(string value);
    partial void Onf_UsernameChanged();
    partial void Onf_PasswordChanging(string value);
    partial void Onf_PasswordChanged();
    partial void Onf_NameChanging(string value);
    partial void Onf_NameChanged();
    partial void Onf_EmailChanging(string value);
    partial void Onf_EmailChanged();
    partial void Onf_DOBChanging(System.DateTime value);
    partial void Onf_DOBChanged();
    partial void Onf_PermissionChanging(int value);
    partial void Onf_PermissionChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int f_ID
		{
			get
			{
				return this._f_ID;
			}
			set
			{
				if ((this._f_ID != value))
				{
					this.Onf_IDChanging(value);
					this.SendPropertyChanging();
					this._f_ID = value;
					this.SendPropertyChanged("f_ID");
					this.Onf_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string f_Username
		{
			get
			{
				return this._f_Username;
			}
			set
			{
				if ((this._f_Username != value))
				{
					this.Onf_UsernameChanging(value);
					this.SendPropertyChanging();
					this._f_Username = value;
					this.SendPropertyChanged("f_Username");
					this.Onf_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_Password", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string f_Password
		{
			get
			{
				return this._f_Password;
			}
			set
			{
				if ((this._f_Password != value))
				{
					this.Onf_PasswordChanging(value);
					this.SendPropertyChanging();
					this._f_Password = value;
					this.SendPropertyChanged("f_Password");
					this.Onf_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string f_Name
		{
			get
			{
				return this._f_Name;
			}
			set
			{
				if ((this._f_Name != value))
				{
					this.Onf_NameChanging(value);
					this.SendPropertyChanging();
					this._f_Name = value;
					this.SendPropertyChanged("f_Name");
					this.Onf_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string f_Email
		{
			get
			{
				return this._f_Email;
			}
			set
			{
				if ((this._f_Email != value))
				{
					this.Onf_EmailChanging(value);
					this.SendPropertyChanging();
					this._f_Email = value;
					this.SendPropertyChanged("f_Email");
					this.Onf_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime f_DOB
		{
			get
			{
				return this._f_DOB;
			}
			set
			{
				if ((this._f_DOB != value))
				{
					this.Onf_DOBChanging(value);
					this.SendPropertyChanging();
					this._f_DOB = value;
					this.SendPropertyChanged("f_DOB");
					this.Onf_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_Permission", DbType="Int NOT NULL")]
		public int f_Permission
		{
			get
			{
				return this._f_Permission;
			}
			set
			{
				if ((this._f_Permission != value))
				{
					this.Onf_PermissionChanging(value);
					this.SendPropertyChanging();
					this._f_Permission = value;
					this.SendPropertyChanged("f_Permission");
					this.Onf_PermissionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
